version: "3"

services:
  strapi:
    container_name: strapi-azure-container
    image: evodim/strapi-azure:preview
    volumes:
      - ./app/api:/srv/app/api
      - ./app/components:/srv/app/components      
    environment:
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
      - STORAGE_ACCOUNT=${STORAGE_ACCOUNT}
      - STORAGE_ACCOUNT_KEY=${STORAGE_ACCOUNT_KEY}
      - STORAGE_URL=${STORAGE_URL}
      - STORAGE_CONTAINER_NAME=${STORAGE_CONTAINER_NAME}
      - STORAGE_CDN_URL=${STORAGE_CDN_URL}
      - STORAGE_DEFAULT_PATH=${STORAGE_DEFAULT_PATH}
      - STORAGE_MAX_CONCURRENT=${STORAGE_MAX_CONCURRENT}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}      
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
